### ISSUE TITLE
A different target formulation

### ISSUE THREAD

**Issue by aishwaryyasarkar** [nklingen/Transformer-Time-Series-Forecasting#4]
Hi,

First of all, I loved your post on Medium. This is my first time implementing a Transformer, so I have a few doubts. Looking at your data and how you designed your problem, I think you were trying to predict the future feature value for each of your sensors? Is this correct? If so, would it still work for the following scenario?

To simplify, suppose I have 10 sensors. All 9 of them contribute to the 10th sensor on a particular day, and I have chunks of similar daily data. So I want the model first to learn the correlation between the 9 sensors and the 10th (using just their features, of course), which is essential to predict the future feature value of sensor 10.

(I know a GNN would be able to handle the correlation more efficiently, but I was wondering if Transformer alone would also be able to do this)

Please let me know if this is outside your area of interest. Since you seem way deeper into the concept of Transformers, I thought I might ask.

I really appreciate any help you can provide.

**Comment by natashaklingenbrunn** [comment]
Thanks for your message, I'm happy you enjoyed the Medium article :)
 
From my understanding, your goal is to forecast a sensor x, but you also have additional sensors that are correlated with the value of sensor x. In this case, you could try adding the other sensors as additional features in the transformer input.
