### ISSUE TITLE
General questions regarding your modal

### ISSUE THREAD

**Issue by sarraAyed** [nklingen/Transformer-Time-Series-Forecasting#7]
- Is it possible to use the seconds as positional encoding instead of the cos and sinus ?
- I don't understand the use of reindexed_id 
- Is there an efficient way to choose the epoch, k and frequency and the forecast_window, or is a trial and error
- Usually to train a model, we use a dataset for training, testing and validating.  In this case you ommited the last one, is there a reason ?

**Comment by natashaklingenbrunn** [comment]
Hi,
- If your data varies over seconds, then you should include the seconds as a feature as well, but I would think it still makes sense to encode them with sin/cos as they are cyclical.
- reindexed_id was relevant for reindexing my original dataset, but this was specific to my case.
- You could use sweeps to optimise hyperparameter tuning, but generally this is trial and error
- best practice is to use train/val/test sets
